# syntax=docker/dockerfile:1.7
# Multi-stage, distroless-style build.
# requirements.txt is generated by pip-compile --generate-hashes so the
# --require-hashes flag below is always satisfied. Regenerate with:
#   pip-compile --generate-hashes app/requirements.in -o app/requirements.txt
#
# Base image: pin to a digest for full supply-chain integrity.
# Update the digest when upgrading Python or applying security patches:
#   docker pull python:3.12-slim-bookworm
#   docker inspect python:3.12-slim-bookworm --format '{{index .RepoDigests 0}}'
ARG PYTHON_VERSION=3.12-slim-bookworm
# sha256 below is the digest for 3.12-slim-bookworm as of the last review.
# Replace with the output of the inspect command above before production use.
ARG PYTHON_DIGEST=sha256:e9b6a30f2b3ded7ad1b94e7c5f88492bea44c2f17ee09c0c16c2a6db5e7db1d4

FROM python:${PYTHON_VERSION}@${PYTHON_DIGEST} AS builder
WORKDIR /build
ENV PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PYTHONDONTWRITEBYTECODE=1
COPY app/requirements.txt ./requirements.txt
# --require-hashes: fail the build if any wheel/sdist is not hash-pinned.
# --no-deps: transitives must be listed explicitly in requirements.txt
#            (pip-compile --generate-hashes resolves them all).
# No silent fallback -- if this fails, regenerate requirements.txt.
RUN python -m venv /venv \
    && /venv/bin/pip install --require-hashes --no-deps -r requirements.txt

FROM python:${PYTHON_VERSION}@${PYTHON_DIGEST} AS runtime
# Drop privileges: run as non-root, read-only filesystem-friendly layout.
RUN groupadd --system --gid 10001 app \
    && useradd  --system --uid 10001 --gid app --no-create-home --shell /usr/sbin/nologin app
WORKDIR /srv/app
COPY --from=builder /venv /venv
COPY app/ /srv/app/app/
ENV PATH="/venv/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    APP_VERSION=dev
USER 10001:10001
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
    CMD python -c "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/healthz').status==200 else 1)"
ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "2", "app.app:app"]